# Introduction to `polars`

Based on https://docs.pola.rs/user-guide/getting-started/

## Installation

In [1]:
!uv add polars

Resolved 31 packages in 2.67s
⠙ Preparing packages... (0/2)                                                   ⠋ Preparing packages... (0/0)
⠙ Preparing packages... (0/2)-------------------     0 B/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 14.79 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 30.79 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 46.79 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 62.79 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 78.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 94.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 110.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 126.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 142.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 158.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 174.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 190.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 206.05 KiB/53.79 MiB
⠙ Preparing packages... (0/2)------------------- 222.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 238.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 238.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 254.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 270.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 286.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 302.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 334.05 KiB/53.79 MiB
⠹ Preparing packages... (0/2)------------------- 430.05 KiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠹ Preparing packages... (0/2)------------------- 606.05 KiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 1.11 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 1.46 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 2.06 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 2.62 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 2.78 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 2.97 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 3.12 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 3.51 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 4.00 MiB/53.79 MiB
polars               ------------------------------ 16.00 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 4.48 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 5.11 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 5.40 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 5.53 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 5.80 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 5.94 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 6.17 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠧ Preparing packages... (0/2)------------------- 6.48 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠧ Preparing packages... (0/2)------------------- 7.03 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠧ Preparing packages... (0/2)------------------- 7.40 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠧ Preparing packages... (0/2)------------------- 7.92 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠇ Preparing packages... (0/2)------------------- 8.50 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠇ Preparing packages... (0/2)------------------- 8.73 MiB/53.79 MiB
polars               ------------------------------ 32.00 KiB/813.91 KiB
⠇ Preparing packages... (0/2)------------------- 9.15 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠇ Preparing packages... (0/2)------------------- 9.39 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠋ Preparing packages... (0/2)------------------- 9.90 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠋ Preparing packages... (0/2)------------------- 10.33 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠋ Preparing packages... (0/2)------------------- 10.78 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠋ Preparing packages... (0/2)------------------- 11.22 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠙ Preparing packages... (0/2)------------------- 11.65 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠙ Preparing packages... (0/2)------------------- 12.09 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠙ Preparing packages... (0/2)------------------- 12.38 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠙ Preparing packages... (0/2)------------------- 12.63 MiB/53.79 MiB
polars               ------------------------------ 48.00 KiB/813.91 KiB
⠹ Preparing packages... (0/2)------------------- 12.85 MiB/53.79 MiB
polars               ------------------------------ 62.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)------------------- 13.30 MiB/53.79 MiB
polars               ------------------------------ 62.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)------------------- 13.76 MiB/53.79 MiB
polars               ------------------------------ 62.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)------------------- 14.31 MiB/53.79 MiB
polars               ------------------------------ 62.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 14.89 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 15.25 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 15.92 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)------------------- 16.50 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 17.06 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 17.64 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 18.03 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)------------------- 18.50 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 18.92 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 19.37 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 19.67 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)------------------- 20.20 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 20.69 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)------------------- 21.26 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)m------------------ 21.75 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)m------------------ 22.31 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)m------------------ 22.64 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)m------------------ 22.86 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)m------------------ 23.15 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)2m----------------- 23.59 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)2m----------------- 24.22 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)2m----------------- 24.53 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)2m----------------- 24.79 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)[2m---------------- 25.22 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)[2m---------------- 25.44 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)[2m---------------- 25.82 MiB/53.79 MiB
polars               ------------------------------ 78.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)[2m---------------- 26.23 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)[2m---------------- 26.47 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠙ Preparing packages... (0/2)[2m---------------- 26.69 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠙ Preparing packages... (0/2)--------------- 27.14 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠙ Preparing packages... (0/2)--------------- 27.25 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠙ Preparing packages... (0/2)--------------- 27.69 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)--------------- 28.12 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)--------------- 28.33 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)--------------- 28.64 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)m-------------- 28.80 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)m-------------- 29.00 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)m-------------- 29.28 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)m-------------- 29.75 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)m-------------- 30.22 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)m-------------- 30.36 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)0m------------- 30.59 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)0m------------- 31.29 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)0m------------- 31.81 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)30m------------ 32.37 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)30m------------ 32.84 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)30m------------ 33.23 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)30m------------ 33.58 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)30m------------ 33.98 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)[30m----------- 34.54 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)[30m----------- 35.06 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)[30m----------- 35.64 MiB/53.79 MiB
polars               ------------------------------ 94.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 36.31 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 36.84 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 37.42 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 37.97 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 38.31 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 38.56 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 38.67 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 38.92 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)---------- 39.37 MiB/53.79 MiB
polars               ------------------------------ 110.54 KiB/813.91 KiB
⠋ Preparing packages... (0/2)---------- 39.79 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠋ Preparing packages... (0/2)---------- 40.27 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠋ Preparing packages... (0/2)---------- 40.86 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠙ Preparing packages... (0/2)---------- 41.20 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠙ Preparing packages... (0/2)---------- 41.79 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠙ Preparing packages... (0/2)---------- 42.25 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠙ Preparing packages... (0/2)---------- 42.40 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠹ Preparing packages... (0/2)---------- 42.81 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠹ Preparing packages... (0/2)---------- 43.27 MiB/53.79 MiB
polars               ------------------------------ 126.43 KiB/813.91 KiB
⠹ Preparing packages... (0/2)---------- 43.62 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠹ Preparing packages... (0/2)---------- 44.06 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)---------- 44.36 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)---------- 44.64 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)---------- 45.12 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠸ Preparing packages... (0/2)---------- 45.47 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)---------- 45.95 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)---------- 46.07 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)---------- 46.23 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠼ Preparing packages... (0/2)---------- 46.55 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)---------- 46.92 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)---------- 47.11 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)---------- 47.29 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠴ Preparing packages... (0/2)---------- 47.54 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)---------- 47.85 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)---------- 48.44 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)---------- 49.00 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠦ Preparing packages... (0/2)---------- 49.61 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 50.22 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 50.58 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 50.94 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠧ Preparing packages... (0/2)---------- 51.22 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 51.39 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB
⠇ Preparing packages... (0/2)---------- 51.70 MiB/53.79 MiB
polars               ------------------------------ 142.54 KiB/813.91 KiB

## Reading & writing

In [2]:
import polars as pl
import datetime as dt

df = pl.DataFrame(
    {
        "name": ["Alice Archer", "Ben Brown", "Chloe Cooper", "Daniel Donovan"],
        "birthdate": [
            dt.date(1997, 1, 10),
            dt.date(1985, 2, 15),
            dt.date(1983, 3, 22),
            dt.date(1981, 4, 30),
        ],
        "weight": [57.9, 72.5, 53.6, 83.1],  # (kg)
        "height": [1.56, 1.77, 1.65, 1.75],  # (m)
    }
)

print(df)

shape: (4, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ date       ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
└────────────────┴────────────┴────────┴────────┘

In [5]:
df.write_csv("output.csv")
df_csv = pl.read_csv("output.csv", try_parse_dates=True)
df_csv

shape: (4, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ date       ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
└────────────────┴────────────┴────────┴────────┘

In [ ]:
df.write_json("output.json")
df_json = pl.read_json("output.json")
df_json

shape: (4, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ str        ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
└────────────────┴────────────┴────────┴────────┘